"""GreenCoin — Action Routes (log, history, types)"""
from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from sqlalchemy.orm import Session
from sqlalchemy import desc
from pydantic import BaseModel
from typing import Optional, List, Any
from datetime import datetime
import uuid

from database import get_db
from models.action import GreenAction
from models.user import User
from routes.auth import get_current_user
from config import settings

router = APIRouter(prefix="/actions", tags=["actions"])


# ── Schemas ───────────────────────────────────────────────────────────────────
class LogActionRequest(BaseModel):
    action_type: str
    quantity: float = 1.0
    proof_data: dict = {}
    notes: Optional[str] = None


class ActionOut(BaseModel):
    id: str
    action_type: str
    quantity: float
    verification_status: str
    trust_score: Optional[int]
    credits_earned: float
    timestamp: datetime
    fraud_flags: List[Any] = []

    class Config:
        from_attributes = True


class ActionTypeInfo(BaseModel):
    code: str
    display_name: str
    category: str
    credits_per_unit: float
    unit: str
    description: str
    icon: str
    max_daily_claim: float


ACTION_TYPE_CATALOG = [
    {"code": "cycling_commute",  "display_name": "Cycling Commute",   "category": "transport",
     "credits_per_unit": 4,  "unit": "km",       "description": "Commute by bicycle instead of car",        "icon": "🚴", "max_daily_claim": 60},
    {"code": "public_transport", "display_name": "Public Transport",   "category": "transport",
     "credits_per_unit": 2,  "unit": "km",       "description": "Travel by bus, metro, or train",           "icon": "🚌", "max_daily_claim": 100},
    {"code": "plant_based_meal", "display_name": "Plant-Based Meal",   "category": "diet",
     "credits_per_unit": 5,  "unit": "meal",     "description": "Choose a plant-based meal over meat",      "icon": "🥗", "max_daily_claim": 25},
    {"code": "solar_energy",     "display_name": "Solar Energy Usage", "category": "energy",
     "credits_per_unit": 10, "unit": "kWh",      "description": "Energy generated by rooftop solar",       "icon": "☀️", "max_daily_claim": 500},
    {"code": "composting",       "display_name": "Home Composting",    "category": "waste",
     "credits_per_unit": 3,  "unit": "kg",       "description": "Compost organic waste instead of landfill","icon": "♻️", "max_daily_claim": 30},
    {"code": "ev_charging",      "display_name": "EV Charging",        "category": "energy",
     "credits_per_unit": 8,  "unit": "kWh",      "description": "Charge electric vehicle vs fuel car",     "icon": "⚡", "max_daily_claim": 200},
    {"code": "led_switch",       "display_name": "LED Bulb Switch",    "category": "energy",
     "credits_per_unit": 20, "unit": "one-time", "description": "Replace incandescent bulbs with LED",     "icon": "💡", "max_daily_claim": 20},
    {"code": "no_flight",        "display_name": "Avoided Flight",     "category": "transport",
     "credits_per_unit": 50, "unit": "flight",   "description": "Take train or call instead of flying",    "icon": "✈️", "max_daily_claim": 50},
]


# ── Endpoints ─────────────────────────────────────────────────────────────────
@router.get("/types", response_model=List[ActionTypeInfo])
def get_action_types():
    """Return all available action types with credit rates."""
    return ACTION_TYPE_CATALOG


@router.post("/log", status_code=201)
async def log_action(
    data: LogActionRequest,
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Log a green action. Runs TrustVerifier and mints credits in background."""
    # Validate action type
    valid_types = {a["code"] for a in ACTION_TYPE_CATALOG}
    if data.action_type not in valid_types:
        raise HTTPException(400, f"Unknown action type: {data.action_type}")

    action = GreenAction(
        user_id=current_user.id,
        action_type_code=data.action_type,
        quantity=data.quantity,
        proof_data=data.proof_data,
        notes=data.notes,
        verification_status="pending",
    )
    db.add(action)
    db.commit()
    db.refresh(action)

    # Run verification + credit minting asynchronously
    background_tasks.add_task(_verify_and_mint, str(action.id))

    return {
        "action_id": str(action.id),
        "status": "pending",
        "message": "Action logged successfully. Verification in progress.",
    }


def _verify_and_mint(action_id: str):
    """Background task: run ML verification and mint credits."""
    from database import SessionLocal
    from ml.trust_verify import TrustVerifier
    from services.credit_minter import CreditMinter

    db = SessionLocal()
    try:
        action = db.query(GreenAction).filter(GreenAction.id == action_id).first()
        if not action:
            return

        verifier = TrustVerifier()
        result = verifier.verify_action({
            "user_id": str(action.user_id),
            "action_type": action.action_type_code,
            "quantity": action.quantity,
            "proof_data": action.proof_data,
            "timestamp": action.timestamp.isoformat(),
        })

        action.trust_score = result["trust_score"]
        action.fraud_flags = result["flags"]

        if result["trust_score"] >= 50:
            action.verification_status = "verified"
            minter = CreditMinter(db)
            minted = minter.mint(action, result["trust_score"])
            action.credits_earned = minted["credits_minted"]
        else:
            action.verification_status = "rejected"

        db.commit()
    finally:
        db.close()


@router.get("/history", response_model=List[ActionOut])
def get_history(
    skip: int = 0,
    limit: int = 20,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    actions = (
        db.query(GreenAction)
        .filter(GreenAction.user_id == current_user.id)
        .order_by(desc(GreenAction.timestamp))
        .offset(skip)
        .limit(limit)
        .all()
    )
    return [
        ActionOut(
            id=str(a.id),
            action_type=a.action_type_code,
            quantity=a.quantity,
            verification_status=a.verification_status,
            trust_score=a.trust_score,
            credits_earned=a.credits_earned,
            timestamp=a.timestamp,
            fraud_flags=a.fraud_flags or [],
        )
        for a in actions
    ]
